import StoreProvider from "@/lib/Provider/StoreProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Redux Typescript Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="font-questrial">
          <>
            <Toaster position="top-center" />
            {children}
          </>
        </body>
      </html>
    </StoreProvider>
  );
}
